### ISSUE TITLE
Using old version of MSSQL

### ISSUE THREAD

**Issue by burkkyy** [icefoganalytics/internal-data-portal#117]
On a clean pull of this repo, `dev up` fails due to a bad db healthcheck.

## Context
There was a new update to [mcr.microsoft.com/mssql/server:2022-latest](http://mcr.microsoft.com/mssql/server:2022-latest) and this causes the healthcheck in the docker compose `db` service to fail. This is due to the path of sqlcmd being changed in an update.

Use the following to get image hash (As of Jul 23, 2024)
```bash
$ docker inspect --format='{{index .RepoDigests 0}}' mcr.microsoft.com/mssql/server:2022-latest
mcr.microsoft.com/mssql/server@sha256:c1aa8afe9b06eab64c9774a4802dcd032205d1be785b1fd51e1c0151e7586b74 # Expected output
```
If your hash is different, your are running an old version of [mcr.microsoft.com/mssql/server:2022-latest](http://mcr.microsoft.com/mssql/server:2022-latest)
To prevent headaches, use the following mssql docker image version in docker compose:
[mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04](http://mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04)
Example:
```yaml
db:
    image: mcr.microsoft.com/mssql/server:2022-CU13-ubuntu-22.04
    user: root
    environment:
      <<: *default-environment
      AZURE_SQL_HOST: "localhost"
      DB_HOST: "localhost"
      MSSQL_SA_PASSWORD: *default-db-password
      TZ: "America/Whitehorse"
      ACCEPT_EULA: "Y"
```

## Additional context
Related to https://github.com/icefoganalytics/project-budgeting/issues/20
